name: build

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: always()

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: bun install
        run: bun install --ignore-scripts

      - name: bun build:dist
        run: bun build:dist

      - name: bun test
        run: bun test
