name: build

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: bun install
        run: bun i --frozen-lockfile

      - name: bun build:dist
        run: bun build:dist

      - name: bun test
        run: bun test
